### ISSUE TITLE
error during CMake and compiling error in VS2019

### ISSUE THREAD

**Issue by hduonggithub** [trlsmax/imgui-vtk#1]
![image](https://user-images.githubusercontent.com/11492480/93150229-2b5dad00-f6be-11ea-89b9-6f0883a0d52e.png)

![image](https://user-images.githubusercontent.com/11492480/93150255-39133280-f6be-11ea-9aa5-a8ad2ac96220.png)

Please help! Thanks

**Comment by trlsmax** [comment]
GLFW3_LIBRARY should be the file path of glfw library, eg : E:/projects/glfw-3.3.2.bin.WIN64/lib-vc2019/glfw3dll.lib
![微信截图_20200915133709](https://user-images.githubusercontent.com/5501321/93169858-a5427480-f758-11ea-9b06-73836eee8a9e.png)

**Comment by hduonggithub** [comment]
Hi @trlsmax,

It works perfectly now.
![image](https://user-images.githubusercontent.com/11492480/93216347-3c91d280-f72d-11ea-9faa-42f5e185c462.png)

**Comment by hduonggithub** [comment]
Hi @trlsmax 

Have you heard about this modification (https://github.com/PointCloudLibrary/pcl/issues/3831) made to Point Cloud Library (PCL). It modified the VTK and added imgui in PCL module for GUI instead of using Qt. Do you think it is possible to add your changes in here to the VTK in PCL module?

Here is what they said:
![image](https://user-images.githubusercontent.com/11492480/93218403-ccd11700-f72f-11ea-9adb-7bcf57d48cec.png)

**Comment by trlsmax** [comment]
Hi
I'm sorry I haven't used PCL before.
Code in here just let VTK render into texture and draw the texture in background.
Maybe you can try to find a way to let PCL render into texture and draw it in background or IMGUI window.
Good luck.

**Comment by hduonggithub** [comment]
Hi @trlsmax 

Sorry for another question.

How can I import and display my point cloud into this Viewer? I am trying to find a way to replace the sphere?

**Comment by trlsmax** [comment]
Just add actor into renderer

**Comment by hduonggithub** [comment]
Hi @trlsmax 

Thanks for prompt reply. Can you please provide a bit more details? Like where in the code I should modify. Thanks!

**Comment by trlsmax** [comment]
Please read doc of vtk for how to render object.
I'll close this now.
