### ISSUE TITLE
Error during compilation with VTK 8.2.0

### ISSUE THREAD

**Issue by capitan-davide** [trlsmax/imgui-vtk#4]
Hi,

I am trying to compile with Visual Studio 16 2019, VTK 9.0.1 is working fine but with VTK 8.2.0 I am having the following errors:

`class "vtkGenericOpenGLRenderWindow" has no member "UseOffScreenBuffersOff"`
`class "vtkGenericOpenGLRenderWindow" has no member "SetShowWindow"`

Is there a VTK 8.2 compatible way to do this? Thank you for your answer.

Regards

**Comment by trlsmax** [comment]
Just push a new commit. Please try and let me know if it works.

**Comment by capitan-davide** [comment]
Thank you. the vtkOutputWindow is spamming warnings but once you close that the ImGUI vtk window becomes responsive and seems to be working

![vtkOutputWindow](https://user-images.githubusercontent.com/18486238/98248320-0fb3ac00-1f75-11eb-80f8-e22e32f95af8.png)
.
